# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  package = read_json(json_path: "../package.json")
  version = package[:version]

  private_lane :versioning do

    increment_version_code(
        gradle_file_path: "./app/build.gradle",
    )

    increment_version_name(
        gradle_file_path: "./app/build.gradle",
        version_name: version
    )
  end
  
  private_lane :notify_discord do
    discord_notifier(
      webhook_url:"",
      title: "Nova versão",
      description: "Build da versão #{version} criada com sucesso!",
      success: true
    )
  end

  desc "Build a new version of the app"
  lane :build do
    gradle(task: "clean assembleRelease")
    notify_discord
  end
end

